/**
 * 用户可见能力的轻量导航索引。
 *
 * 本文件由 tools/generate-capability-matrix.mjs 根据能力目录生成。
 * 请勿手工修改；运行 npm.cmd run generate:capabilities 更新。
 */
export const CAPABILITY_LABELS = {
  "top.dashboard": "工作台",
  "top.favorites": "收藏夹",
  "top.channel": "营业渠道",
  "top.periodicals": "报刊业务",
  "top.accounting": "账务处理",
  "top.philately": "集邮服务",
  "more.distribution": "分销业务",
  "more.points": "积分业务",
  "more.settlement": "结算处理",
  "more.analytics": "综合数据",
  "management.business": "业务管理",
  "management.basic": "基础管理",
  "channel.business.recommendation": "业务推荐",
  "channel.business.intake": "综合受理",
  "channel.business.bulk": "大宗处理",
  "channel.business.overlay-entry": "网点叠加业务补录",
  "channel.business.commercial-bulk": "商函邮件大宗处理",
  "channel.business.public-welfare-bulk": "公益邮件大宗处理",
  "channel.business.correction": "查改处理",
  "channel.business.refund": "退款待办查询",
  "channel.business.return-receipt": "回执寄回办理",
  "channel.business.reply-coupon": "国际回信券兑付",
  "channel.business.self-service-import": "客户自助批量导入",
  "channel.business.settlement-correction": "结算方式查改",
  "channel.business.channel-sales-entry": "多渠道商品简易销售",
  "channel.business.channel-sales-query": "多渠道商品综合销售查改",
  "channel.business.insurance": "保险业务受理",
  "channel.dispatch.handover": "交接处理",
  "channel.dispatch.sealing": "封发处理",
  "channel.dispatch.route": "路单生成",
  "channel.dispatch.print": "路单/清单打印",
  "channel.dispatch.export": "趟车出口",
  "channel.dispatch.query": "封发查询",
  "channel.dispatch.interchange-return": "总包退回互换局",
  "channel.special.application": "邮件撤改处理",
  "channel.special.status": "邮件改址撤回状态查询",
  "channel.window.import": "窗投进口处理",
  "channel.window.supplement": "窗投补录",
  "channel.window.return-receive": "投递转退邮件接收",
  "channel.window.transfer-receive": "投递转窗投邮件接收",
  "channel.window.maintenance": "窗投查改",
  "channel.window.transfer": "窗投转退",
  "channel.window.reminder": "窗投催领逾退",
  "channel.window.cancellation": "窗投销号",
  "channel.window.balance": "窗投平衡统计",
  "channel.window.query": "窗投查询统计",
  "channel.meter.handover-out": "委托交出处理",
  "channel.meter.handover-in": "委托接收处理",
  "channel.meter.batch": "过戳批次管理",
  "channel.meter.registration": "过戳登记",
  "channel.meter.balance": "批次过戳平衡",
  "channel.meter.daily": "日终平衡",
  "channel.meter.funding": "注资申请",
  "channel.meter.repair": "报修启用",
  "channel.meter.maintenance": "邮资机信息维护",
  "channel.meter.handover-history": "邮资机历史交接信息查询",
  "channel.meter.usage-ledger": "邮资机使用登记簿查询",
  "channel.supplies.inbound": "用邮物品入库",
  "channel.supplies.requisition": "用邮物品请领",
  "channel.supplies.approval": "用邮物品审批",
  "channel.supplies.receipt": "用邮物品接收",
  "channel.supplies.issue": "用邮物品下发",
  "channel.supplies.return": "用邮物品退回",
  "channel.supplies.inventory": "用邮物品库存盘点",
  "channel.supplies.balance": "用邮物品平衡统计",
  "channel.supplies.sales": "用邮物品销售统计",
  "channel.commercial-bill": "商函账单处理",
  "channel.invoice.legacy-red": "票据冲红处理",
  "channel.invoice.financial-red": "业财发票冲红",
  "channel.query.third-party-payment": "第三方支付查询",
  "channel.query.front-desk-log": "前台日志查询",
  "channel.query.mail-tracking": "给据邮件跟踪查询",
  "channel.query.accepted-mail": "收寄邮件查询",
  "channel.query.route-comparison": "邮路对照查询",
  "channel.query.network-export": "网运出口关系查询",
  "channel.query.branch-export": "寄递支局出口关系查询",
  "channel.query.vehicle-dispatch": "车辆派车信息查询",
  "channel.query.spot-check": "抽查演练信息查询",
  "channel.query.postal-administrative": "邮编行政区划查询",
  "channel.query.inspection-mailbox": "巡视类专用邮政信箱查询",
  "channel.query.customer": "营业客户查询",
  "channel.query.offline-loan": "线下贷款申请管理",
  "channel.points.inventory": "商品库存管理",
  "channel.points.redemption": "积分兑换",
  "channel.points.history": "兑换历史查询",
  "channel.points.statistics": "积分兑换统计",
  "help.capability-matrix": "功能成熟度",
  "help.operation": "操作帮助",
} as const

export type PublicCapabilityId = keyof typeof CAPABILITY_LABELS

export function getCapabilityLabel(capabilityId: PublicCapabilityId): string {
  return CAPABILITY_LABELS[capabilityId]
}
