export type AdministrativeDivisionLevel = 'province' | 'prefecture' | 'county'

export interface AdministrativeDivision {
  id: string
  parentId: string | null
  body: string
  suffix: string
  fullName: string
  level: AdministrativeDivisionLevel
  role: string
  capitalId: string | null
}

// Curated fictional hierarchy imported from the user-approved Markdown catalog.
// Business routing semantics remain independent from these display names.
export const ADMINISTRATIVE_DIVISIONS = [
  {"id":"P001","parentId":null,"body":"瀚原","suffix":"省","fullName":"瀚原省","level":"province","role":"","capitalId":"F001"},
  {"id":"P002","parentId":null,"body":"澄岐","suffix":"省","fullName":"澄岐省","level":"province","role":"","capitalId":"F004"},
  {"id":"P003","parentId":null,"body":"砚岭","suffix":"省","fullName":"砚岭省","level":"province","role":"","capitalId":"F007"},
  {"id":"P004","parentId":null,"body":"霁川","suffix":"省","fullName":"霁川省","level":"province","role":"","capitalId":"F010"},
  {"id":"P005","parentId":null,"body":"汐陵","suffix":"省","fullName":"汐陵省","level":"province","role":"","capitalId":"F013"},
  {"id":"P006","parentId":null,"body":"朔汀","suffix":"省","fullName":"朔汀省","level":"province","role":"","capitalId":"F016"},
  {"id":"P007","parentId":null,"body":"岚海","suffix":"省","fullName":"岚海省","level":"province","role":"","capitalId":"F019"},
  {"id":"P008","parentId":null,"body":"衡沚","suffix":"省","fullName":"衡沚省","level":"province","role":"","capitalId":"F022"},
  {"id":"P009","parentId":null,"body":"清垣","suffix":"省","fullName":"清垣省","level":"province","role":"","capitalId":"F025"},
  {"id":"P010","parentId":null,"body":"望川","suffix":"省","fullName":"望川省","level":"province","role":"","capitalId":"F028"},
  {"id":"P011","parentId":null,"body":"容岭","suffix":"省","fullName":"容岭省","level":"province","role":"","capitalId":"F031"},
  {"id":"P012","parentId":null,"body":"昭野","suffix":"省","fullName":"昭野省","level":"province","role":"","capitalId":"F034"},
  {"id":"P013","parentId":null,"body":"景原","suffix":"省","fullName":"景原省","level":"province","role":"","capitalId":"F037"},
  {"id":"P014","parentId":null,"body":"江岑","suffix":"省","fullName":"江岑省","level":"province","role":"","capitalId":"F040"},
  {"id":"P015","parentId":null,"body":"岭澈","suffix":"省","fullName":"岭澈省","level":"province","role":"","capitalId":"F043"},
  {"id":"P016","parentId":null,"body":"泽原","suffix":"省","fullName":"泽原省","level":"province","role":"","capitalId":"F046"},
  {"id":"P017","parentId":null,"body":"浦岳","suffix":"省","fullName":"浦岳省","level":"province","role":"","capitalId":"F049"},
  {"id":"P018","parentId":null,"body":"宁岫","suffix":"省","fullName":"宁岫省","level":"province","role":"","capitalId":"F052"},
  {"id":"P019","parentId":null,"body":"沧汀","suffix":"省","fullName":"沧汀省","level":"province","role":"","capitalId":"F055"},
  {"id":"P020","parentId":null,"body":"鹤原","suffix":"省","fullName":"鹤原省","level":"province","role":"","capitalId":"F058"},
  {"id":"P021","parentId":null,"body":"云砾","suffix":"省","fullName":"云砾省","level":"province","role":"","capitalId":"F061"},
  {"id":"P022","parentId":null,"body":"澜陆","suffix":"省","fullName":"澜陆省","level":"province","role":"","capitalId":"F064"},
  {"id":"P023","parentId":null,"body":"青岑","suffix":"自治区","fullName":"青岑自治区","level":"province","role":"","capitalId":"F067"},
  {"id":"P024","parentId":null,"body":"白澈","suffix":"自治区","fullName":"白澈自治区","level":"province","role":"","capitalId":"F070"},
  {"id":"P025","parentId":null,"body":"松垣","suffix":"自治区","fullName":"松垣自治区","level":"province","role":"","capitalId":"F073"},
  {"id":"P026","parentId":null,"body":"丹汀","suffix":"自治区","fullName":"丹汀自治区","level":"province","role":"","capitalId":"F076"},
  {"id":"P027","parentId":null,"body":"曜川","suffix":"自治区","fullName":"曜川自治区","level":"province","role":"","capitalId":"F079"},
  {"id":"P028","parentId":null,"body":"澜京","suffix":"市","fullName":"澜京市","level":"province","role":"行政中心与本级同名","capitalId":"P028"},
  {"id":"P029","parentId":null,"body":"玄津","suffix":"市","fullName":"玄津市","level":"province","role":"行政中心与本级同名","capitalId":"P029"},
  {"id":"P030","parentId":null,"body":"海垣","suffix":"市","fullName":"海垣市","level":"province","role":"行政中心与本级同名","capitalId":"P030"},
  {"id":"P031","parentId":null,"body":"曜城","suffix":"市","fullName":"曜城市","level":"province","role":"行政中心与本级同名","capitalId":"P031"},
  {"id":"P032","parentId":null,"body":"自贸港","suffix":"特别行政区","fullName":"自贸港特别行政区","level":"province","role":"用户指定保留项；行政中心与本级同名","capitalId":"P032"},
  {"id":"P033","parentId":null,"body":"镜海埠","suffix":"特别行政区","fullName":"镜海埠特别行政区","level":"province","role":"用户指定保留项；行政中心与本级同名","capitalId":"P033"},
  {"id":"P034","parentId":null,"body":"美丽岛","suffix":"特别行政区","fullName":"美丽岛特别行政区","level":"province","role":"用户指定保留项；行政中心与本级同名","capitalId":"P034"},
  {"id":"F001","parentId":"P001","body":"栖沄","suffix":"市","fullName":"栖沄市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F002","parentId":"P001","body":"栖岳","suffix":"市","fullName":"栖岳市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F003","parentId":"P001","body":"砚澈","suffix":"市","fullName":"砚澈市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F004","parentId":"P002","body":"澄野","suffix":"市","fullName":"澄野市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F005","parentId":"P002","body":"霁浦","suffix":"市","fullName":"霁浦市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F006","parentId":"P002","body":"汐原","suffix":"市","fullName":"汐原市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F007","parentId":"P003","body":"砚浦","suffix":"市","fullName":"砚浦市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F008","parentId":"P003","body":"岚垣","suffix":"市","fullName":"岚垣市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F009","parentId":"P003","body":"衡浦","suffix":"市","fullName":"衡浦市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F010","parentId":"P004","body":"霁宁","suffix":"市","fullName":"霁宁市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F011","parentId":"P004","body":"清岳","suffix":"市","fullName":"清岳市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F012","parentId":"P004","body":"望岑","suffix":"市","fullName":"望岑市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F013","parentId":"P005","body":"汐川","suffix":"市","fullName":"汐川市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F014","parentId":"P005","body":"容浦","suffix":"市","fullName":"容浦市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F015","parentId":"P005","body":"昭湾","suffix":"市","fullName":"昭湾市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F016","parentId":"P006","body":"朔原","suffix":"市","fullName":"朔原市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F017","parentId":"P006","body":"景岳","suffix":"市","fullName":"景岳市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F018","parentId":"P006","body":"江汀","suffix":"市","fullName":"江汀市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F019","parentId":"P007","body":"岚津","suffix":"市","fullName":"岚津市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F020","parentId":"P007","body":"岭浦","suffix":"市","fullName":"岭浦市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F021","parentId":"P007","body":"泽岑","suffix":"市","fullName":"泽岑市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F022","parentId":"P008","body":"衡垣","suffix":"市","fullName":"衡垣市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F023","parentId":"P008","body":"浦陵","suffix":"市","fullName":"浦陵市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F024","parentId":"P008","body":"宁野","suffix":"市","fullName":"宁野市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F025","parentId":"P009","body":"清岑","suffix":"市","fullName":"清岑市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F026","parentId":"P009","body":"沧浦","suffix":"市","fullName":"沧浦市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F027","parentId":"P009","body":"鹤岑","suffix":"市","fullName":"鹤岑市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F028","parentId":"P010","body":"望浦","suffix":"市","fullName":"望浦市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F029","parentId":"P010","body":"云汀","suffix":"市","fullName":"云汀市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F030","parentId":"P010","body":"澜野","suffix":"市","fullName":"澜野市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F031","parentId":"P011","body":"容川","suffix":"市","fullName":"容川市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F032","parentId":"P011","body":"青岫","suffix":"市","fullName":"青岫市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F033","parentId":"P011","body":"白野","suffix":"市","fullName":"白野市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F034","parentId":"P012","body":"昭岫","suffix":"市","fullName":"昭岫市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F035","parentId":"P012","body":"松浦","suffix":"市","fullName":"松浦市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F036","parentId":"P012","body":"丹岑","suffix":"市","fullName":"丹岑市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F037","parentId":"P013","body":"景汀","suffix":"市","fullName":"景汀市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F038","parentId":"P013","body":"曜浦","suffix":"市","fullName":"曜浦市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F039","parentId":"P013","body":"玄岑","suffix":"市","fullName":"玄岑市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F040","parentId":"P014","body":"江砚","suffix":"市","fullName":"江砚市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F041","parentId":"P014","body":"海汀","suffix":"市","fullName":"海汀市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F042","parentId":"P014","body":"镜野","suffix":"市","fullName":"镜野市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F043","parentId":"P015","body":"岭宁","suffix":"市","fullName":"岭宁市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F044","parentId":"P015","body":"瀚浦","suffix":"市","fullName":"瀚浦市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F045","parentId":"P015","body":"朔岑","suffix":"市","fullName":"朔岑市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F046","parentId":"P016","body":"泽岫","suffix":"市","fullName":"泽岫市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F047","parentId":"P016","body":"澄浦","suffix":"市","fullName":"澄浦市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F048","parentId":"P016","body":"栖野","suffix":"市","fullName":"栖野市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F049","parentId":"P017","body":"浦原","suffix":"市","fullName":"浦原市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F050","parentId":"P017","body":"砚岫","suffix":"市","fullName":"砚岫市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F051","parentId":"P017","body":"霁垣","suffix":"市","fullName":"霁垣市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F052","parentId":"P018","body":"宁澈","suffix":"市","fullName":"宁澈市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F053","parentId":"P018","body":"汐浦","suffix":"市","fullName":"汐浦市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F054","parentId":"P018","body":"岚野","suffix":"市","fullName":"岚野市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F055","parentId":"P019","body":"沧岑","suffix":"市","fullName":"沧岑市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F056","parentId":"P019","body":"衡岑","suffix":"市","fullName":"衡岑市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F057","parentId":"P019","body":"清浦","suffix":"市","fullName":"清浦市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F058","parentId":"P020","body":"鹤汀","suffix":"市","fullName":"鹤汀市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F059","parentId":"P020","body":"望岫","suffix":"市","fullName":"望岫市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F060","parentId":"P020","body":"容垣","suffix":"市","fullName":"容垣市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F061","parentId":"P021","body":"云垣","suffix":"市","fullName":"云垣市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F062","parentId":"P021","body":"昭川","suffix":"市","fullName":"昭川市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F063","parentId":"P021","body":"景岑","suffix":"市","fullName":"景岑市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F064","parentId":"P022","body":"澜岳","suffix":"市","fullName":"澜岳市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F065","parentId":"P022","body":"江垣","suffix":"市","fullName":"江垣市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F066","parentId":"P022","body":"岭湾","suffix":"市","fullName":"岭湾市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F067","parentId":"P023","body":"青垣","suffix":"市","fullName":"青垣市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F068","parentId":"P023","body":"泽汀","suffix":"市","fullName":"泽汀市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F069","parentId":"P023","body":"浦砾","suffix":"市","fullName":"浦砾市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F070","parentId":"P024","body":"白汀","suffix":"市","fullName":"白汀市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F071","parentId":"P024","body":"宁浦","suffix":"市","fullName":"宁浦市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F072","parentId":"P024","body":"沧野","suffix":"市","fullName":"沧野市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F073","parentId":"P025","body":"松野","suffix":"市","fullName":"松野市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F074","parentId":"P025","body":"鹤浦","suffix":"市","fullName":"鹤浦市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F075","parentId":"P025","body":"云湾","suffix":"市","fullName":"云湾市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F076","parentId":"P026","body":"丹原","suffix":"市","fullName":"丹原市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F077","parentId":"P026","body":"澜岑","suffix":"市","fullName":"澜岑市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F078","parentId":"P026","body":"白垣","suffix":"市","fullName":"白垣市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F079","parentId":"P027","body":"曜岑","suffix":"市","fullName":"曜岑市","level":"prefecture","role":"省会","capitalId":null},
  {"id":"F080","parentId":"P027","body":"松湾","suffix":"市","fullName":"松湾市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F081","parentId":"P027","body":"丹野","suffix":"市","fullName":"丹野市","level":"prefecture","role":"普通地级市","capitalId":null},
  {"id":"F082","parentId":"P001","body":"雪砾","suffix":"地区","fullName":"雪砾地区","level":"prefecture","role":"地区","capitalId":null},
  {"id":"F083","parentId":"P006","body":"寒岫","suffix":"地区","fullName":"寒岫地区","level":"prefecture","role":"地区","capitalId":null},
  {"id":"F084","parentId":"P015","body":"远岫","suffix":"地区","fullName":"远岫地区","level":"prefecture","role":"地区","capitalId":null},
  {"id":"F085","parentId":"P021","body":"瀚漠","suffix":"地区","fullName":"瀚漠地区","level":"prefecture","role":"地区","capitalId":null},
  {"id":"F086","parentId":"P023","body":"霜川","suffix":"地区","fullName":"霜川地区","level":"prefecture","role":"地区","capitalId":null},
  {"id":"F087","parentId":"P027","body":"青漠","suffix":"地区","fullName":"青漠地区","level":"prefecture","role":"地区","capitalId":null},
  {"id":"C001","parentId":"P028","body":"栖台","suffix":"区","fullName":"栖台区","level":"county","role":"直辖市辖区","capitalId":null},
  {"id":"C002","parentId":"P028","body":"栖湾","suffix":"区","fullName":"栖湾区","level":"county","role":"直辖市辖区","capitalId":null},
  {"id":"C003","parentId":"P028","body":"砚桥","suffix":"区","fullName":"砚桥区","level":"county","role":"直辖市辖区","capitalId":null},
  {"id":"C004","parentId":"P029","body":"砚麓","suffix":"区","fullName":"砚麓区","level":"county","role":"直辖市辖区","capitalId":null},
  {"id":"C005","parentId":"P029","body":"霁洲","suffix":"区","fullName":"霁洲区","level":"county","role":"直辖市辖区","capitalId":null},
  {"id":"C006","parentId":"P029","body":"霁门","suffix":"区","fullName":"霁门区","level":"county","role":"直辖市辖区","capitalId":null},
  {"id":"C007","parentId":"P030","body":"汐台","suffix":"区","fullName":"汐台区","level":"county","role":"直辖市辖区","capitalId":null},
  {"id":"C008","parentId":"P030","body":"汐桥","suffix":"区","fullName":"汐桥区","level":"county","role":"直辖市辖区","capitalId":null},
  {"id":"C009","parentId":"P030","body":"岚湾","suffix":"区","fullName":"岚湾区","level":"county","role":"直辖市辖区","capitalId":null},
  {"id":"C010","parentId":"P031","body":"岚麓","suffix":"区","fullName":"岚麓区","level":"county","role":"直辖市辖区","capitalId":null},
  {"id":"C011","parentId":"P031","body":"衡洲","suffix":"区","fullName":"衡洲区","level":"county","role":"直辖市辖区","capitalId":null},
  {"id":"C012","parentId":"P031","body":"衡门","suffix":"区","fullName":"衡门区","level":"county","role":"直辖市辖区","capitalId":null},
  {"id":"C013","parentId":"P032","body":"清台","suffix":"区","fullName":"清台区","level":"county","role":"特别行政区下辖区","capitalId":null},
  {"id":"C014","parentId":"P032","body":"清桥","suffix":"区","fullName":"清桥区","level":"county","role":"特别行政区下辖区","capitalId":null},
  {"id":"C015","parentId":"P032","body":"望湾","suffix":"区","fullName":"望湾区","level":"county","role":"特别行政区下辖区","capitalId":null},
  {"id":"C016","parentId":"P033","body":"望麓","suffix":"区","fullName":"望麓区","level":"county","role":"特别行政区下辖区","capitalId":null},
  {"id":"C017","parentId":"P033","body":"容洲","suffix":"区","fullName":"容洲区","level":"county","role":"特别行政区下辖区","capitalId":null},
  {"id":"C018","parentId":"P033","body":"容门","suffix":"区","fullName":"容门区","level":"county","role":"特别行政区下辖区","capitalId":null},
  {"id":"C019","parentId":"P034","body":"昭台","suffix":"区","fullName":"昭台区","level":"county","role":"特别行政区下辖区","capitalId":null},
  {"id":"C020","parentId":"P034","body":"昭桥","suffix":"区","fullName":"昭桥区","level":"county","role":"特别行政区下辖区","capitalId":null},
  {"id":"C021","parentId":"P034","body":"景湾","suffix":"区","fullName":"景湾区","level":"county","role":"特别行政区下辖区","capitalId":null},
  {"id":"C022","parentId":"F001","body":"景麓","suffix":"区","fullName":"景麓区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C023","parentId":"F004","body":"江洲","suffix":"区","fullName":"江洲区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C024","parentId":"F007","body":"江浦","suffix":"区","fullName":"江浦区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C025","parentId":"F010","body":"岭台","suffix":"区","fullName":"岭台区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C026","parentId":"F013","body":"岭门","suffix":"区","fullName":"岭门区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C027","parentId":"F016","body":"泽湾","suffix":"区","fullName":"泽湾区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C028","parentId":"F019","body":"泽桥","suffix":"区","fullName":"泽桥区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C029","parentId":"F022","body":"浦洲","suffix":"区","fullName":"浦洲区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C030","parentId":"F025","body":"浦麓","suffix":"区","fullName":"浦麓区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C031","parentId":"F028","body":"宁台","suffix":"区","fullName":"宁台区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C032","parentId":"F031","body":"宁门","suffix":"区","fullName":"宁门区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C033","parentId":"F034","body":"沧湾","suffix":"区","fullName":"沧湾区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C034","parentId":"F037","body":"沧桥","suffix":"区","fullName":"沧桥区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C035","parentId":"F040","body":"鹤洲","suffix":"区","fullName":"鹤洲区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C036","parentId":"F043","body":"鹤麓","suffix":"区","fullName":"鹤麓区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C037","parentId":"F046","body":"云桥","suffix":"区","fullName":"云桥区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C038","parentId":"F049","body":"云麓","suffix":"区","fullName":"云麓区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C039","parentId":"F052","body":"澜台","suffix":"区","fullName":"澜台区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C040","parentId":"F055","body":"澜湾","suffix":"区","fullName":"澜湾区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C041","parentId":"F058","body":"青桥","suffix":"区","fullName":"青桥区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C042","parentId":"F061","body":"青麓","suffix":"区","fullName":"青麓区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C043","parentId":"F064","body":"白台","suffix":"区","fullName":"白台区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C044","parentId":"F067","body":"白湾","suffix":"区","fullName":"白湾区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C045","parentId":"F070","body":"松桥","suffix":"区","fullName":"松桥区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C046","parentId":"F073","body":"松麓","suffix":"区","fullName":"松麓区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C047","parentId":"F076","body":"丹台","suffix":"区","fullName":"丹台区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C048","parentId":"F079","body":"丹湾","suffix":"区","fullName":"丹湾区","level":"county","role":"市辖区","capitalId":null},
  {"id":"C049","parentId":"F002","body":"栖砾","suffix":"县","fullName":"栖砾县","level":"county","role":"县","capitalId":null},
  {"id":"C050","parentId":"F003","body":"栖沚","suffix":"县","fullName":"栖沚县","level":"county","role":"县","capitalId":null},
  {"id":"C051","parentId":"F005","body":"砚溪","suffix":"县","fullName":"砚溪县","level":"county","role":"县","capitalId":null},
  {"id":"C052","parentId":"F006","body":"砚沚","suffix":"县","fullName":"砚沚县","level":"county","role":"县","capitalId":null},
  {"id":"C053","parentId":"F008","body":"霁砾","suffix":"县","fullName":"霁砾县","level":"county","role":"县","capitalId":null},
  {"id":"C054","parentId":"F009","body":"霁沚","suffix":"县","fullName":"霁沚县","level":"county","role":"县","capitalId":null},
  {"id":"C055","parentId":"F011","body":"汐岫","suffix":"县","fullName":"汐岫县","level":"county","role":"县","capitalId":null},
  {"id":"C056","parentId":"F012","body":"汐砾","suffix":"县","fullName":"汐砾县","level":"county","role":"县","capitalId":null},
  {"id":"C057","parentId":"F014","body":"岚沚","suffix":"县","fullName":"岚沚县","level":"county","role":"县","capitalId":null},
  {"id":"C058","parentId":"F015","body":"衡砾","suffix":"县","fullName":"衡砾县","level":"county","role":"县","capitalId":null},
  {"id":"C059","parentId":"F017","body":"衡谷","suffix":"县","fullName":"衡谷县","level":"county","role":"县","capitalId":null},
  {"id":"C060","parentId":"F018","body":"清砾","suffix":"县","fullName":"清砾县","level":"county","role":"县","capitalId":null},
  {"id":"C061","parentId":"F020","body":"清沚","suffix":"县","fullName":"清沚县","level":"county","role":"县","capitalId":null},
  {"id":"C062","parentId":"F021","body":"望砾","suffix":"县","fullName":"望砾县","level":"county","role":"县","capitalId":null},
  {"id":"C063","parentId":"F023","body":"望沚","suffix":"县","fullName":"望沚县","level":"county","role":"县","capitalId":null},
  {"id":"C064","parentId":"F024","body":"容岫","suffix":"县","fullName":"容岫县","level":"county","role":"县","capitalId":null},
  {"id":"C065","parentId":"F026","body":"容砾","suffix":"县","fullName":"容砾县","level":"county","role":"县","capitalId":null},
  {"id":"C066","parentId":"F027","body":"昭砾","suffix":"县","fullName":"昭砾县","level":"county","role":"县","capitalId":null},
  {"id":"C067","parentId":"F029","body":"景沚","suffix":"县","fullName":"景沚县","level":"county","role":"县","capitalId":null},
  {"id":"C068","parentId":"F030","body":"江岫","suffix":"县","fullName":"江岫县","level":"county","role":"县","capitalId":null},
  {"id":"C069","parentId":"F032","body":"江砾","suffix":"县","fullName":"江砾县","level":"county","role":"县","capitalId":null},
  {"id":"C070","parentId":"F033","body":"岭砾","suffix":"县","fullName":"岭砾县","level":"county","role":"县","capitalId":null},
  {"id":"C071","parentId":"F035","body":"岭沚","suffix":"县","fullName":"岭沚县","level":"county","role":"县","capitalId":null},
  {"id":"C072","parentId":"F036","body":"泽砾","suffix":"县","fullName":"泽砾县","level":"county","role":"县","capitalId":null},
  {"id":"C073","parentId":"F038","body":"泽沚","suffix":"县","fullName":"泽沚县","level":"county","role":"县","capitalId":null},
  {"id":"C074","parentId":"F039","body":"浦溪","suffix":"县","fullName":"浦溪县","level":"county","role":"县","capitalId":null},
  {"id":"C075","parentId":"F041","body":"宁砾","suffix":"县","fullName":"宁砾县","level":"county","role":"县","capitalId":null},
  {"id":"C076","parentId":"F042","body":"宁沚","suffix":"县","fullName":"宁沚县","level":"county","role":"县","capitalId":null},
  {"id":"C077","parentId":"F044","body":"沧岫","suffix":"县","fullName":"沧岫县","level":"county","role":"县","capitalId":null},
  {"id":"C078","parentId":"F045","body":"沧砾","suffix":"县","fullName":"沧砾县","level":"county","role":"县","capitalId":null},
  {"id":"C079","parentId":"F047","body":"鹤砾","suffix":"县","fullName":"鹤砾县","level":"county","role":"县","capitalId":null},
  {"id":"C080","parentId":"F048","body":"鹤沚","suffix":"县","fullName":"鹤沚县","level":"county","role":"县","capitalId":null},
  {"id":"C081","parentId":"F050","body":"云岫","suffix":"县","fullName":"云岫县","level":"county","role":"县","capitalId":null},
  {"id":"C082","parentId":"F051","body":"云沚","suffix":"县","fullName":"云沚县","level":"county","role":"县","capitalId":null},
  {"id":"C083","parentId":"F053","body":"澜砾","suffix":"县","fullName":"澜砾县","level":"county","role":"县","capitalId":null},
  {"id":"C084","parentId":"F054","body":"澜沚","suffix":"县","fullName":"澜沚县","level":"county","role":"县","capitalId":null},
  {"id":"C085","parentId":"F056","body":"青砾","suffix":"县","fullName":"青砾县","level":"county","role":"县","capitalId":null},
  {"id":"C086","parentId":"F057","body":"青沚","suffix":"县","fullName":"青沚县","level":"county","role":"县","capitalId":null},
  {"id":"C087","parentId":"F059","body":"白砾","suffix":"县","fullName":"白砾县","level":"county","role":"县","capitalId":null},
  {"id":"C088","parentId":"F060","body":"白沚","suffix":"县","fullName":"白沚县","level":"county","role":"县","capitalId":null},
  {"id":"C089","parentId":"F062","body":"松砾","suffix":"县","fullName":"松砾县","level":"county","role":"县","capitalId":null},
  {"id":"C090","parentId":"F063","body":"丹沚","suffix":"县","fullName":"丹沚县","level":"county","role":"县","capitalId":null},
  {"id":"C091","parentId":"F065","body":"栖津","suffix":"市","fullName":"栖津市","level":"county","role":"县级市","capitalId":null},
  {"id":"C092","parentId":"F066","body":"砚港","suffix":"市","fullName":"砚港市","level":"county","role":"县级市","capitalId":null},
  {"id":"C093","parentId":"F068","body":"霁安","suffix":"市","fullName":"霁安市","level":"county","role":"县级市","capitalId":null},
  {"id":"C094","parentId":"F069","body":"汐宁","suffix":"市","fullName":"汐宁市","level":"county","role":"县级市","capitalId":null},
  {"id":"C095","parentId":"F071","body":"岚岳","suffix":"市","fullName":"岚岳市","level":"county","role":"县级市","capitalId":null},
  {"id":"C096","parentId":"F072","body":"衡港","suffix":"市","fullName":"衡港市","level":"county","role":"县级市","capitalId":null},
  {"id":"C097","parentId":"F074","body":"清津","suffix":"市","fullName":"清津市","level":"county","role":"县级市","capitalId":null},
  {"id":"C098","parentId":"F075","body":"望宁","suffix":"市","fullName":"望宁市","level":"county","role":"县级市","capitalId":null},
  {"id":"C099","parentId":"F077","body":"容海","suffix":"市","fullName":"容海市","level":"county","role":"县级市","capitalId":null},
  {"id":"C100","parentId":"F078","body":"昭港","suffix":"市","fullName":"昭港市","level":"county","role":"县级市","capitalId":null},
  {"id":"C101","parentId":"F080","body":"景安","suffix":"市","fullName":"景安市","level":"county","role":"县级市","capitalId":null},
  {"id":"C102","parentId":"F081","body":"岭津","suffix":"市","fullName":"岭津市","level":"county","role":"县级市","capitalId":null},
  {"id":"C103","parentId":"F082","body":"泽宁","suffix":"市","fullName":"泽宁市","level":"county","role":"县级市","capitalId":null},
  {"id":"C104","parentId":"F083","body":"浦阳","suffix":"市","fullName":"浦阳市","level":"county","role":"县级市","capitalId":null},
  {"id":"C105","parentId":"F084","body":"沧岳","suffix":"市","fullName":"沧岳市","level":"county","role":"县级市","capitalId":null},
  {"id":"C106","parentId":"F085","body":"鹤宁","suffix":"市","fullName":"鹤宁市","level":"county","role":"县级市","capitalId":null},
  {"id":"C107","parentId":"F086","body":"云港","suffix":"市","fullName":"云港市","level":"county","role":"县级市","capitalId":null},
  {"id":"C108","parentId":"F087","body":"澜安","suffix":"市","fullName":"澜安市","level":"county","role":"县级市","capitalId":null},
  {"id":"C109","parentId":"F001","body":"青津","suffix":"市","fullName":"青津市","level":"county","role":"县级市","capitalId":null},
  {"id":"C110","parentId":"F004","body":"白宁","suffix":"市","fullName":"白宁市","level":"county","role":"县级市","capitalId":null},
  {"id":"C111","parentId":"F007","body":"松港","suffix":"市","fullName":"松港市","level":"county","role":"县级市","capitalId":null},
  {"id":"C112","parentId":"F010","body":"丹安","suffix":"市","fullName":"丹安市","level":"county","role":"县级市","capitalId":null},
  {"id":"C113","parentId":"F082","body":"寒松","suffix":"林区","fullName":"寒松林区","level":"county","role":"林区","capitalId":null},
  {"id":"C114","parentId":"F083","body":"雾岫","suffix":"林区","fullName":"雾岫林区","level":"county","role":"林区","capitalId":null},
  {"id":"C115","parentId":"F084","body":"雪岭","suffix":"林区","fullName":"雪岭林区","level":"county","role":"林区","capitalId":null},
  {"id":"C116","parentId":"F085","body":"霜岑","suffix":"林区","fullName":"霜岑林区","level":"county","role":"林区","capitalId":null},
  {"id":"C117","parentId":"F086","body":"砚谷","suffix":"特区","fullName":"砚谷特区","level":"county","role":"特区","capitalId":null},
  {"id":"C118","parentId":"F087","body":"澄湾","suffix":"特区","fullName":"澄湾特区","level":"county","role":"特区","capitalId":null},
  {"id":"C119","parentId":"F002","body":"瀚岭","suffix":"特区","fullName":"瀚岭特区","level":"county","role":"特区","capitalId":null},
  {"id":"C120","parentId":"F003","body":"曜湾","suffix":"特区","fullName":"曜湾特区","level":"county","role":"特区","capitalId":null},
] as const satisfies readonly AdministrativeDivision[]

export const PROVINCE_DIVISIONS = ADMINISTRATIVE_DIVISIONS.filter(
  (division) => division.level === 'province',
)

const ADDRESS_PICKER_PROVINCE_IDS = [
  'P028',
  'P029',
  'P001',
  'P002',
  'P003',
  'P004',
  'P005',
  'P006',
  'P030',
  'P007',
  'P008',
  'P009',
  'P010',
  'P011',
  'P012',
  'P013',
  'P014',
  'P015',
  'P016',
  'P017',
  'P018',
  'P019',
  'P020',
  'P021',
  'P022',
  'P031',
  'P023',
  'P024',
  'P025',
  'P026',
  'P027',
  'P034',
  'P032',
  'P033',
] as const

const provinceDivisionById = new Map<string, AdministrativeDivision>(
  PROVINCE_DIVISIONS.map((division) => [division.id, division]),
)

export const ADDRESS_PICKER_PROVINCES = ADDRESS_PICKER_PROVINCE_IDS.map((id) => {
  const division = provinceDivisionById.get(id)
  if (!division) throw new Error(`Missing address-picker province ${id}`)
  return division
})

export const PREFECTURE_DIVISIONS = ADMINISTRATIVE_DIVISIONS.filter(
  (division) => division.level === 'prefecture',
)

export const COUNTY_DIVISIONS = ADMINISTRATIVE_DIVISIONS.filter(
  (division) => division.level === 'county',
)

export const LOCAL_PREFECTURE_ID = 'F001'
