import type {
  AccessInstitution,
  AccessPermission,
  AccessRole,
  OperatorProfile,
} from './types'

export const DEFAULT_OPERATOR_PROFILE: OperatorProfile = {
  displayName: '演示营业员',
  nameAbbreviation: 'YSYY',
  identityCode: '990101199001010011',
  gender: 'male',
  personnelStatus: 'active',
  birthDate: '1990-01-01',
  phone: '10000000009',
  institutionCode: '99901001',
  institutionName: '景麓营业部',
  employedDate: '2020-07-01',
  serviceYears: '6年1个月',
  arrivalDate: '2020-07-01',
  departureDate: '',
  mentalOutlook: 'good',
  personnelType: 'contract-a',
  workplaceRole: 'counter-service',
  jobCategory: 'service',
  directSupervisor: '90000001',
  educationLevel: 'college',
  professionalQualification: 'none',
  reliefPermission: 'disabled',
  jobInformation: 'counter-operator',
  reliefEligible: false,
  reliefRoleIds: [],
  receiveSmsType: 'business-and-security',
  receiveSmsTime: '08:00-20:00',
  responsibleStoreOutlet: '景麓营业部',
  performanceSourceOutlet: '景麓营业部',
  performanceEvaluation: '良好',
}

export const MANAGEMENT_OPERATOR_PROFILE: OperatorProfile = {
  ...DEFAULT_OPERATOR_PROFILE,
  displayName: '演示主管',
  nameAbbreviation: 'YSZG',
  identityCode: '990101198802020019',
  birthDate: '1988-02-02',
  phone: '10000000010',
  employedDate: '2016-03-01',
  serviceYears: '10年5个月',
  arrivalDate: '2019-04-01',
  workplaceRole: 'operations',
  jobCategory: 'management',
  directSupervisor: '91000001',
  jobInformation: 'shift-supervisor',
  performanceEvaluation: '优秀',
}

export const UPPER_MANAGEMENT_OPERATOR_PROFILE: OperatorProfile = {
  ...MANAGEMENT_OPERATOR_PROFILE,
  displayName: '演示市级人员审批员',
  nameAbbreviation: 'YSSJRYSPY',
  identityCode: '990101198503030016',
  birthDate: '1985-03-03',
  phone: '10000000011',
  institutionCode: '99900100',
  institutionName: '栖沄市业务管理中心',
  employedDate: '2012-02-01',
  serviceYears: '14年6个月',
  arrivalDate: '2018-05-01',
  workplaceRole: 'operations',
  jobCategory: 'management',
  directSupervisor: '92000001',
  jobInformation: 'operations-support',
  responsibleStoreOutlet: '景麓营业部',
  performanceSourceOutlet: '栖沄市业务管理中心',
}

export const COUNTER_OPERATOR_PROFILE: OperatorProfile = {
  ...DEFAULT_OPERATOR_PROFILE,
  displayName: '演示网点营业人员',
  nameAbbreviation: 'YSWDYYRY',
  identityCode: '990101199107070019',
  birthDate: '1991-07-07',
  phone: '10000000014',
  jobInformation: 'outlet-business-operator',
}

export const ROLE_ADMIN_OPERATOR_PROFILE: OperatorProfile = {
  ...UPPER_MANAGEMENT_OPERATOR_PROFILE,
  displayName: '演示角色管理员',
  nameAbbreviation: 'YSJSGLY',
  identityCode: '990101198404040018',
  birthDate: '1984-04-04',
  phone: '10000000012',
  institutionCode: '99900000',
  institutionName: '瀚原业务管理中心',
  workplaceRole: 'access-governance',
  jobCategory: 'management',
  jobInformation: 'role-administrator',
  performanceSourceOutlet: '瀚原业务管理中心',
}

export const PERSONNEL_CLERK_OPERATOR_PROFILE: OperatorProfile = {
  ...UPPER_MANAGEMENT_OPERATOR_PROFILE,
  displayName: '演示县级人员经办员',
  nameAbbreviation: 'YSXJRYJBY',
  identityCode: '990101199006060016',
  birthDate: '1990-06-06',
  phone: '10000000013',
  institutionCode: '99901000',
  institutionName: '景麓区运营中心',
  workplaceRole: 'personnel-processing',
  jobCategory: 'management',
  jobInformation: 'county-personnel-operator',
  performanceSourceOutlet: '景麓区运营中心',
}

export const ACCESS_INSTITUTIONS: AccessInstitution[] = [
  {
    code: '99900000',
    name: '瀚原业务管理中心',
    parentCode: null,
    level: 'province',
    status: 'active',
  },
  {
    code: '99900100',
    name: '栖沄市业务管理中心',
    parentCode: '99900000',
    level: 'prefecture',
    status: 'active',
  },
  {
    code: '99901000',
    name: '景麓区运营中心',
    parentCode: '99900100',
    level: 'county',
    status: 'active',
  },
  {
    code: '99901001',
    name: '景麓营业部',
    parentCode: '99901000',
    level: 'outlet',
    status: 'active',
  },
]

export const ACCESS_PERMISSION_LABELS: Record<AccessPermission, string> = {
  'workspace.dashboard': '工作台与个人工作区',
  'workspace.channel.access': '营业渠道入口',
  'workspace.channel.core': '营业渠道核心受理',
  'workspace.channel.bulk': '大宗邮件处理',
  'workspace.channel.dispatch': '邮件封发',
  'workspace.channel.dispatch.handover': '交接处理入口',
  'workspace.channel.dispatch.handover-out': '散件交出',
  'workspace.channel.dispatch.handover-in': '邮件与总包接收',
  'workspace.channel.dispatch.sealing': '封发处理',
  'workspace.channel.dispatch.routing': '路单生成与打印',
  'workspace.channel.dispatch.transport': '趟车出口交接',
  'workspace.channel.dispatch.query': '封发查询',
  'workspace.channel.dispatch.interchange-return': '总包退回互换局',
  'workspace.channel.special': '特殊处理',
  'workspace.channel.window-delivery': '窗投业务',
  'workspace.channel.postage-meter': '邮资机业务',
  'workspace.channel.postal-supply': '用邮物品管理',
  'workspace.channel.invoice': '票据管理',
  'workspace.channel.query': '营业查询',
  'workspace.channel.points': '积分业务',
  'workspace.periodicals': '报刊业务',
  'workspace.accounting': '账务处理',
  'workspace.philately': '集邮服务',
  'workspace.distribution': '分销业务',
  'workspace.insurance': '保险业务受理',
  'management.basic.access': '基础管理入口',
  'management.basic.personnel': '人员管理',
  'management.basic.roles': '角色管理',
  'management.basic.dispatch-relations': '封发关系管理',
  'management.business.access': '业务管理入口',
  'management.business.attendance.read': '签到签退查询',
  'management.business.attendance.operate': '签到签退操作',
  'management.business.on-site-authorization': '主管现场一次性授权',
  'management.business.personnel-approval': '人员审批',
  'management.business.role-approval': '岗位角色审批',
  'management.permission.request': '岗位与权限申请',
}

const counterPermissions: AccessPermission[] = [
  'workspace.dashboard',
  'workspace.channel.access',
  'workspace.channel.core',
  'workspace.channel.bulk',
  'workspace.channel.dispatch',
  'workspace.channel.dispatch.handover',
  'workspace.channel.dispatch.handover-out',
  'workspace.channel.dispatch.handover-in',
  'workspace.channel.dispatch.sealing',
  'workspace.channel.dispatch.routing',
  'workspace.channel.dispatch.transport',
  'workspace.channel.dispatch.query',
  'workspace.channel.dispatch.interchange-return',
  'workspace.channel.query',
  'workspace.accounting',
  'management.business.access',
  'management.business.attendance.read',
  'management.permission.request',
]

const supervisorPermissions: AccessPermission[] = [
  'workspace.dashboard',
  'workspace.accounting',
  'management.business.access',
  'management.business.attendance.read',
  'management.business.attendance.operate',
  'management.business.on-site-authorization',
]

const employeeDutyPermissions: AccessPermission[] = [
  'management.business.access',
  'management.business.attendance.read',
]

export const ACCESS_ROLES: AccessRole[] = [
  {
    id: 'counter-operator',
    name: '网点基础营业权限',
    system: 'production',
    level: 'outlet',
    permissions: counterPermissions,
    custom: false,
    status: 'active',
  },
  {
    id: 'outlet-supervisor',
    name: '营业主管管理权限',
    system: 'management',
    level: 'outlet',
    permissions: supervisorPermissions,
    custom: false,
    status: 'active',
  },
  {
    id: 'special-handling-operator',
    name: '特殊处理权限',
    system: 'production',
    level: 'outlet',
    permissions: ['workspace.dashboard', 'workspace.channel.access', 'workspace.channel.special', ...employeeDutyPermissions],
    custom: true,
    status: 'active',
  },
  {
    id: 'window-delivery-operator',
    name: '窗投业务权限',
    system: 'production',
    level: 'outlet',
    permissions: ['workspace.dashboard', 'workspace.channel.access', 'workspace.channel.window-delivery', ...employeeDutyPermissions],
    custom: true,
    status: 'active',
  },
  {
    id: 'postage-meter-manager',
    name: '邮资机业务权限',
    system: 'production',
    level: 'outlet',
    permissions: ['workspace.dashboard', 'workspace.channel.access', 'workspace.channel.postage-meter', ...employeeDutyPermissions],
    custom: true,
    status: 'active',
  },
  {
    id: 'postal-supply-manager',
    name: '用邮物品业务权限',
    system: 'production',
    level: 'outlet',
    permissions: ['workspace.dashboard', 'workspace.channel.access', 'workspace.channel.postal-supply', ...employeeDutyPermissions],
    custom: true,
    status: 'active',
  },
  {
    id: 'invoice-manager',
    name: '票据业务权限',
    system: 'production',
    level: 'outlet',
    permissions: ['workspace.dashboard', 'workspace.channel.access', 'workspace.channel.invoice', ...employeeDutyPermissions],
    custom: true,
    status: 'active',
  },
  {
    id: 'periodicals-operator',
    name: '报刊业务权限',
    system: 'production',
    level: 'outlet',
    permissions: ['workspace.dashboard', 'workspace.periodicals', ...employeeDutyPermissions],
    custom: true,
    status: 'active',
  },
  {
    id: 'accounting-operator',
    name: '账务处理权限',
    system: 'production',
    level: 'outlet',
    permissions: ['workspace.dashboard', 'workspace.accounting', ...employeeDutyPermissions],
    custom: true,
    status: 'active',
  },
  {
    id: 'philately-operator',
    name: '集邮业务权限',
    system: 'production',
    level: 'outlet',
    permissions: ['workspace.dashboard', 'workspace.philately', ...employeeDutyPermissions],
    custom: true,
    status: 'active',
  },
  {
    id: 'distribution-operator',
    name: '分销业务权限',
    system: 'production',
    level: 'outlet',
    permissions: ['workspace.dashboard', 'workspace.distribution', ...employeeDutyPermissions],
    custom: true,
    status: 'active',
  },
  {
    id: 'insurance-assistant',
    name: '保险业务权限',
    system: 'production',
    level: 'outlet',
    permissions: ['workspace.dashboard', 'workspace.insurance', ...employeeDutyPermissions],
    custom: true,
    status: 'active',
  },
  {
    id: 'points-operator',
    name: '积分业务权限',
    system: 'production',
    level: 'outlet',
    permissions: ['workspace.dashboard', 'workspace.channel.access', 'workspace.channel.points', ...employeeDutyPermissions],
    custom: true,
    status: 'active',
  },
  {
    id: 'basic-management-assistant',
    name: '已停用基础管理权限',
    system: 'management',
    level: 'outlet',
    permissions: [
      'workspace.dashboard',
    ],
    custom: false,
    status: 'inactive',
  },
  {
    id: 'personnel-clerk',
    name: '县级人员经办权限',
    system: 'management',
    level: 'county',
    permissions: [
      'workspace.dashboard',
      'management.basic.access',
      'management.basic.personnel',
      'management.basic.dispatch-relations',
    ],
    custom: false,
    status: 'active',
  },
  {
    id: 'personnel-administrator',
    name: '市级人员审批权限',
    system: 'management',
    level: 'prefecture',
    permissions: [
      'workspace.dashboard',
      'management.business.access',
      'management.business.personnel-approval',
    ],
    custom: false,
    status: 'active',
  },
  {
    id: 'role-administrator',
    name: '省级角色管理权限',
    system: 'management',
    level: 'province',
    permissions: [
      'workspace.dashboard',
      'management.basic.access',
      'management.basic.roles',
      'management.business.access',
      'management.business.role-approval',
    ],
    custom: false,
    status: 'active',
  },
]

export const REQUESTABLE_ROLE_IDS = [
  'special-handling-operator',
  'window-delivery-operator',
  'postage-meter-manager',
  'postal-supply-manager',
  'invoice-manager',
  'periodicals-operator',
  'accounting-operator',
  'philately-operator',
  'distribution-operator',
  'insurance-assistant',
  'points-operator',
] as const

export const REQUESTABLE_ROLE_BY_PERMISSION: Partial<Record<AccessPermission, string>> = {
  'workspace.channel.special': 'special-handling-operator',
  'workspace.channel.window-delivery': 'window-delivery-operator',
  'workspace.channel.postage-meter': 'postage-meter-manager',
  'workspace.channel.postal-supply': 'postal-supply-manager',
  'workspace.channel.invoice': 'invoice-manager',
  'workspace.channel.points': 'points-operator',
  'workspace.periodicals': 'periodicals-operator',
  'workspace.philately': 'philately-operator',
  'workspace.distribution': 'distribution-operator',
  'workspace.insurance': 'insurance-assistant',
}
